#!/bin/bash

cd $(dirname "$0")/.. || exit

inotifywait -m -e close_write -r \
    _config.py _filters _posts _templates brandon \
| while read line
do
    echo 'Building...'
    _v/bin/blogofile build
    echo 'Done.'
done
