#!/bin/bash

set -e

cd $(dirname "$0")
cd ..
rm -rf _v
python3.3 ~/usr/src/virtualenv/virtualenv.py _v

hg clone \
    https://bitbucket.org/brandon/foundations-of-python-network-programming \
    _listings_fopnp

cd _v
. ./bin/activate

pip install docutils==0.10
pip install lxml
pip install mock
pip install Blogofile
pip install blogofile_blog

sed -e 's/docutils==0.9.1/docutils==0.10/' \
    _v/lib/python3.3/site-packages/Blogofile-0.8b1-py3.3.egg-info/requires.txt
